/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/mecha.glb 
*/

import React, { Suspense, useEffect, useRef } from "react"
import { Canvas } from "@react-three/fiber"
import { useFBX } from "@react-three/drei"
import { useAnimations } from "@react-three/drei"
import { OrbitControls, Preload, useGLTF } from "@react-three/drei"
import CanvasLoader from "../Loader" 

const Mecha = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/sci-fi_camera_drone.glb')
  const { actions, names } = useAnimations(animations, group)
  console.log(names)
  useEffect(()=>{
    actions[names[0]].reset().fadeIn(0.5).play()
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="dd9199c0bcaf48598b27c65c00137130fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object013" rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_7" position={[0, 151.718, 70.189]} rotation={[-Math.PI / 2, 0, 0]} />
                    <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.M_0_0} skeleton={nodes.Object_8.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/sci-fi_camera_drone.glb')

const MechaCanvas = () => {
  return (
    <Canvas
      
      gl={{ preserveDrawingBuffer: true }}
      camera={{position : [1,1.5,2.5], fov:50}}
    
    >

     
      <ambientLight intensity={5} />
      
      <Suspense fallback={<CanvasLoader />}>
        <OrbitControls
        enableZoom={false}
        enablePan={false}
        
        />
        <group position={[0,-1.5,0]}  scale={0.01}>
          
          <Mecha />
        </group>
        
      </Suspense>

    </Canvas>
  )
}

export default MechaCanvas;
